entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websesecure
          scheme: https

  websecure:
    address: ":443"
    tls: {}

retry:
  attempts: 4
  initialInterval: 5s

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    domain: pygeoapi.io
    exposedbydefault = false

accessLog:
  filePath: /var/log/traefik/access.log

certificateResolvers:
  default:
    acme:
      domain: demo.pygeoapi.io
      email: just@justobjects.nl
      storage: /acme.json
      tlsChallenge: {}
